application: courseplannerdemo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  login: required

- url: /
  static_files: FrontEnd/dist/index.html
  upload: FrontEnd/dist/index.html
  login: required

- url: /scripts/
  static_dir: FrontEnd/dist/scripts/
  login: required
  auth_fail_action: unauthorized

- url: /api/.*
  script: main.app
  login: required
  auth_fail_action: unauthorized

libraries:
- name: webapp2
  version: "2.5.2"
